import React, { useState } from 'react';
import { LandParcel, StateName } from '../types';
import { X, Save, Edit3, MapPin, Building, ShieldCheck, DollarSign, RefreshCw, AlertTriangle } from 'lucide-react';

interface EditLandDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  land: LandParcel;
  onSave: (updatedLand: LandParcel) => void;
}

export const EditLandDetailsModal: React.FC<EditLandDetailsModalProps> = ({
  isOpen,
  onClose,
  land,
  onSave,
}) => {
  const [name, setName] = useState(land.name);
  const [lotNumber, setLotNumber] = useState(land.lotNumber);
  const [ownershipType, setOwnershipType] = useState(land.ownershipType);
  const [mukim, setMukim] = useState(land.mukim);
  const [district, setDistrict] = useState(land.district);
  const [state, setState] = useState<StateName>(land.state);
  const [areaAcres, setAreaAcres] = useState(land.areaAcres);
  const [landTitleType, setLandTitleType] = useState(land.landTitleType);
  const [remainingLeaseYears, setRemainingLeaseYears] = useState(land.remainingLeaseYears || 99);
  const [categoryOfLandUse, setCategoryOfLandUse] = useState(land.categoryOfLandUse);
  const [expressConditions, setExpressConditions] = useState(land.expressConditions || 'Syarat Nyata: Tanaman Agrikultur / Kebenaran Utiliti Solar');
  const [estimatedLandCostPerAcreMyr, setEstimatedLandCostPerAcreMyr] = useState(land.estimatedLandCostPerAcreMyr || 45000);
  const [notes, setNotes] = useState(land.notes || '');

  if (!isOpen) return null;

  const handleSave = () => {
    const updatedAcres = Math.max(10, Number(areaAcres) || 100);
    const updatedHectares = Math.round(updatedAcres * 0.404686 * 10) / 10;
    const costPerAcre = Math.max(1000, Number(estimatedLandCostPerAcreMyr) || 45000);
    const updatedTotalLandCostMyr = Math.round(((updatedAcres * costPerAcre) / 1000000) * 100) / 100;

    const updatedParcel: LandParcel = {
      ...land,
      name,
      lotNumber,
      ownershipType,
      mukim,
      district,
      state,
      areaAcres: updatedAcres,
      areaHectares: updatedHectares,
      landTitleType,
      remainingLeaseYears: Number(remainingLeaseYears) || 99,
      categoryOfLandUse,
      expressConditions,
      estimatedLandCostPerAcreMyr: costPerAcre,
      estimatedTotalLandAcquisitionCostMyr: updatedTotalLandCostMyr,
      landCapExMyr: updatedTotalLandCostMyr,
      notes: notes || `User-specified land parameters entered manually on ${new Date().toLocaleDateString()}. Subject to JUPEM eCadastre title verification.`,
    };

    onSave(updatedParcel);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/70 backdrop-blur-sm flex items-center justify-center p-4 overflow-y-auto font-sans">
      <div className="bg-white border border-slate-300 w-full max-w-2xl rounded-lg shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="bg-slate-900 px-6 py-4 border-b border-slate-800 flex items-center justify-between text-white">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-amber-500 text-slate-950 font-black rounded flex items-center justify-center">
              <Edit3 className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">Enter / Edit Custom Land Parcel & Ownership Details</h2>
              <p className="text-[11px] text-amber-300 font-mono">
                Input verified Lot Numbers, real Owner details, or JUPEM classification data
              </p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <div className="p-6 overflow-y-auto space-y-4 text-xs font-sans">
          <div className="bg-amber-50 border border-amber-200 p-3 rounded text-amber-900 flex items-start gap-2">
            <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
            <p className="text-[11px]">
              <strong>JUPEM & PTG Ownership Verification Disclaimer:</strong> Standard candidate land plots generated by spatial algorithms are unverified estimates. Use this form to override with real cadastral lot details, land titles, or verified owner names.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Plot Reference Name</label>
              <input
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 font-bold focus:border-amber-500 outline-none"
                placeholder="e.g. Lot 1482 Mukim Bakri"
              />
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Official Lot Number (Geran / Lot PT)</label>
              <input
                type="text"
                value={lotNumber}
                onChange={(e) => setLotNumber(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 font-mono font-bold focus:border-amber-500 outline-none"
                placeholder="e.g. Lot 8921 / PT 14002"
              />
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1 flex items-center gap-1">
                <Building className="w-3.5 h-3.5 text-slate-500" /> Land Ownership & Classification
              </label>
              <select
                value={ownershipType}
                onChange={(e) => setOwnershipType(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 font-semibold focus:border-amber-500 outline-none"
              >
                <option value="Unverified / Candidate Plot (Pending JUPEM Title Search)">
                  Unverified / Candidate Plot (Pending JUPEM Title Search)
                </option>
                <option value="Unverified - Potential Private Land">Unverified - Potential Private Land</option>
                <option value="Unverified - Potential Plantation / Agri Land">Unverified - Potential Plantation / Agri Land</option>
                <option value="Unverified - Potential State Land (Perbadanan Negeri)">
                  Unverified - Potential State Land (Perbadanan Negeri)
                </option>
                <option value="Custom User-Specified Land Plot">Custom User-Specified Land Plot (Manual Entry)</option>
                <option value="Private Owner">Private Individual Owner (Verified)</option>
                <option value="Corporate Agri (Candidate Estate)">Corporate Agri Estate (Verified)</option>
                <option value="FELDA / FELKRA Plantation">FELDA / FELKRA Land Rights</option>
                <option value="State Land (Perbadanan Negeri)">State Land / Perbadanan Negeri (Verified)</option>
                <option value="Industrial Park Corp">Industrial Park Corporation</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Land Area (Acres)</label>
              <input
                type="number"
                value={areaAcres}
                onChange={(e) => setAreaAcres(Number(e.target.value))}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 font-bold focus:border-amber-500 outline-none"
                placeholder="e.g. 150"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                ~ {Math.round(areaAcres * 0.404686 * 10) / 10} Hectares | Approx {Math.round((areaAcres / 2.8) * 10) / 10} MW solar export capacity
              </span>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Land Title Type</label>
              <select
                value={landTitleType}
                onChange={(e) => setLandTitleType(e.target.value as any)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
              >
                <option value="Freehold (Geran Kekal)">Freehold (Geran Kekal / Pegangan Bebas)</option>
                <option value="Leasehold (Mukim Register)">Leasehold (Pajakan Negeri / Mukim)</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Remaining Lease Tenure (Years)</label>
              <input
                type="number"
                value={remainingLeaseYears}
                onChange={(e) => setRemainingLeaseYears(Number(e.target.value))}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
                placeholder="e.g. 99 for Freehold, or 60-99 for Leasehold"
              />
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Mukim</label>
              <input
                type="text"
                value={mukim}
                onChange={(e) => setMukim(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
                placeholder="e.g. Mukim Sidam Kiri"
              />
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">District (Daerah)</label>
              <input
                type="text"
                value={district}
                onChange={(e) => setDistrict(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
                placeholder="e.g. Kuala Muda"
              />
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1">Category of Land Use (Kategori Tanah)</label>
              <select
                value={categoryOfLandUse}
                onChange={(e) => setCategoryOfLandUse(e.target.value as any)}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
              >
                <option value="Agricultural (Oil Palm)">Agricultural (Oil Palm Plantation)</option>
                <option value="Agricultural (Rubber)">Agricultural (Rubber Plantation)</option>
                <option value="Former Mining / Tin Reclamation">Former Mining / Tin Reclamation (Bekas Lombong)</option>
                <option value="Unutilized Scrubland">Unutilized Scrubland (Tanah Terbiar)</option>
                <option value="Industrial Buffer Zone">Industrial Buffer Zone (Perindustrian)</option>
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-slate-700 mb-1 flex items-center gap-1">
                <DollarSign className="w-3.5 h-3.5 text-slate-500" /> Estimated Price / Lease Rate (MYR / Acre)
              </label>
              <input
                type="number"
                value={estimatedLandCostPerAcreMyr}
                onChange={(e) => setEstimatedLandCostPerAcreMyr(Number(e.target.value))}
                className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 font-bold focus:border-amber-500 outline-none"
                placeholder="e.g. 45000"
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Total Land CapEx: RM{' '}
                {(((areaAcres || 0) * (estimatedLandCostPerAcreMyr || 0)) / 1000000).toFixed(2)} Million
              </span>
            </div>
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">Express Conditions (Syarat Nyata / Catatan Title)</label>
            <input
              type="text"
              value={expressConditions}
              onChange={(e) => setExpressConditions(e.target.value)}
              className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
              placeholder="e.g. Syarat Nyata: Tanaman Kelapa Sawit (Perlu Kelulusan Seksyen 124 KTN)"
            />
          </div>

          <div>
            <label className="block text-[11px] font-bold text-slate-700 mb-1">Additional Custom Notes</label>
            <textarea
              rows={2}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full bg-white border border-slate-300 rounded px-2.5 py-1.5 text-slate-900 focus:border-amber-500 outline-none"
              placeholder="Add details regarding landowner contact, JUPEM survey number, or PTG consent status..."
            />
          </div>
        </div>

        {/* Footer Actions */}
        <div className="bg-slate-50 px-6 py-3 border-t border-slate-200 flex items-center justify-between">
          <div className="text-[11px] text-slate-500 font-mono flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-600" /> JUPEM eCadastre Search Compatibility Mode
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-1.5 rounded text-xs font-bold bg-slate-200 hover:bg-slate-300 text-slate-700 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              className="px-4 py-1.5 rounded text-xs font-bold bg-amber-500 hover:bg-amber-400 text-slate-950 transition-colors flex items-center gap-1.5 shadow cursor-pointer"
            >
              <Save className="w-4 h-4 text-slate-950" /> Save Custom Land Data
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
